export type Person = {
  id: number;
  firstName: string;
  lastName: string;
  image: string;
  age: number;
  visits: number;
  status: string;
};

export type PersonData = Person;

export const StaticPersonData: Person[] = [
  {
    id: 1,
    firstName: 'population',
    lastName: 'wdpw7',
    age: 1,
    visits: 13,
    status: '',
    image: '/image.png',
  },
  {
    id: 2,
    firstName: 'feet',
    lastName: 'grq7l',
    age: 18,
    visits: 75,
    status: '',
    image: '/image.png',
  },
  {
    id: 3,
    firstName: 'home',
    lastName: '9l8bf',
    age: 23,
    visits: 32,
    status: '',
    image: '/image.png',
  },
  {
    id: 4,
    firstName: 'home',
    lastName: '9l8bf',
    age: 23,
    visits: 32,
    status: '',
    image: '/image.png',
  },
  {
    id: 5,
    firstName: 'home',
    lastName: '9l8bf',
    age: 23,
    visits: 32,
    status: '',
    image: '/image.png',
  },
  {
    id: 6,
    firstName: 'home',
    lastName: '9l8bf',
    age: 23,
    visits: 32,
    status: '',
    image: '/image.png',
  },
  {
    id: 7,
    firstName: 'home',
    lastName: '9l8bf',
    age: 23,
    visits: 32,
    status: '',
    image: '/image.png',
  },
  {
    id: 8,
    firstName: 'home',
    lastName: '9l8bf',
    age: 23,
    visits: 32,
    status: '',
    image: '/image.png',
  },
  {
    id: 9,
    firstName: 'home',
    lastName: '9l8bf',
    age: 23,
    visits: 32,
    status: '',
    image: '/image.png',
  },
  {
    id: 10,
    firstName: 'home',
    lastName: '9l8bf',
    age: 23,
    visits: 32,
    status: '',
    image: '/image.png',
  },
  {
    id: 11,
    firstName: 'home',
    lastName: '9l8bf',
    age: 23,
    visits: 32,
    status: '',
    image: '/image.png',
  },
  {
    id: 12,
    firstName: 'home',
    lastName: '9l8bf',
    age: 23,
    visits: 32,
    status: '',
    image: '/image.png',
  },
  {
    id: 13,
    firstName: 'population',
    lastName: 'wdpw7',
    age: 1,
    visits: 13,
    status: '',
    image: '/image.png',
  },
  {
    id: 14,
    firstName: 'feet',
    lastName: 'grq7l',
    age: 18,
    visits: 75,
    status: '',
    image: '/image.png',
  },
  {
    id: 15,
    firstName: 'home',
    lastName: '9l8bf',
    age: 23,
    visits: 32,
    status: '',
    image: '/image.png',
  },
  {
    id: 16,
    firstName: 'home',
    lastName: '9l8bf',
    age: 23,
    visits: 32,
    status: '',
    image: '/image.png',
  },
  {
    id: 17,
    firstName: 'home',
    lastName: '9l8bf',
    age: 23,
    visits: 32,
    status: '',
    image: '/image.png',
  },
  {
    id: 18,
    firstName: 'home',
    lastName: '9l8bf',
    age: 23,
    visits: 32,
    status: '',
    image: '/image.png',
  },
  {
    id: 19,
    firstName: 'home',
    lastName: '9l8bf',
    age: 23,
    visits: 32,
    status: '',
    image: '/image.png',
  },
  {
    id: 20,
    firstName: 'home',
    lastName: '9l8bf',
    age: 23,
    visits: 32,
    status: '',
    image: '/image.png',
  },
  {
    id: 21,
    firstName: 'home',
    lastName: '9l8bf',
    age: 23,
    visits: 32,
    status: '',
    image: '/image.png',
  },
  {
    id: 22,
    firstName: 'home',
    lastName: '9l8bf',
    age: 23,
    visits: 32,
    status: '',
    image: '/image.png',
  },
  {
    id: 23,
    firstName: 'home',
    lastName: '9l8bf',
    age: 23,
    visits: 32,
    status: '',
    image: '/image.png',
  },
  {
    id: 24,
    firstName: 'home',
    lastName: '9l8bf',
    age: 23,
    visits: 32,
    status: '',
    image: '/image.png',
  },
  {
    id: 25,
    firstName: 'population',
    lastName: 'wdpw7',
    age: 1,
    visits: 13,
    status: '',
    image: '/image.png',
  },
  {
    id: 26,
    firstName: 'feet',
    lastName: 'grq7l',
    age: 18,
    visits: 75,
    status: '',
    image: '/image.png',
  },
  {
    id: 27,
    firstName: 'home',
    lastName: '9l8bf',
    age: 23,
    visits: 32,
    status: '',
    image: '/image.png',
  },
  {
    id: 28,
    firstName: 'home',
    lastName: '9l8bf',
    age: 23,
    visits: 32,
    status: '',
    image: '/image.png',
  },
  {
    id: 29,
    firstName: 'home',
    lastName: '9l8bf',
    age: 23,
    visits: 32,
    status: '',
    image: '/image.png',
  },
  {
    id: 30,
    firstName: 'home',
    lastName: '9l8bf',
    age: 23,
    visits: 32,
    status: '',
    image: '/image.png',
  },
  {
    id: 31,
    firstName: 'home',
    lastName: '9l8bf',
    age: 23,
    visits: 32,
    status: '',
    image: '/image.png',
  },
  {
    id: 32,
    firstName: 'home',
    lastName: '9l8bf',
    age: 23,
    visits: 32,
    status: '',
    image: '/image.png',
  },
  {
    id: 33,
    firstName: 'home',
    lastName: '9l8bf',
    age: 23,
    visits: 32,
    status: '',
    image: '/image.png',
  },
  {
    id: 34,
    firstName: 'home',
    lastName: '9l8bf',
    age: 23,
    visits: 32,
    status: '',
    image: '/image.png',
  },
  {
    id: 35,
    firstName: 'home',
    lastName: '9l8bf',
    age: 23,
    visits: 32,
    status: '',
    image: '/image.png',
  },
  {
    id: 36,
    firstName: 'home',
    lastName: '9l8bf',
    age: 23,
    visits: 32,
    status: '',
    image: '/image.png',
  },
];
