export type Person = {
  id: number;
  firstName: string;
  lastName: string;
  image: string;
  age: number;
  visits: number;
  status: string;
};

export type PersonData = Person;

export const StaticPersonData: Person[] = [
  {
    id: 10,
    firstName: 'population',
    lastName: 'wdpw7',
    age: 1,
    visits: 13,
    status: '',
    image: '/image.png',
  },
  {
    id: 11,
    firstName: 'feet',
    lastName: 'grq7l',
    age: 18,
    visits: 75,
    status: '',
    image: '/image.png',
  },
  {
    id: 12,
    firstName: 'home',
    lastName: '9l8bf',
    age: 23,
    visits: 32,
    status: '',
    image: '/image.png',
  },
  {
    id: 13,
    firstName: 'home',
    lastName: '9l8bf',
    age: 23,
    visits: 32,
    status: '',
    image: '/image.png',
  },
  {
    id: 14,
    firstName: 'home',
    lastName: '9l8bf',
    age: 23,
    visits: 32,
    status: '',
    image: '/image.png',
  },
  {
    id: 15,
    firstName: 'home',
    lastName: '9l8bf',
    age: 23,
    visits: 32,
    status: '',
    image: '/image.png',
  },
  {
    id: 16,
    firstName: 'home',
    lastName: '9l8bf',
    age: 23,
    visits: 32,
    status: '',
    image: '/image.png',
  },
  {
    id: 17,
    firstName: 'home',
    lastName: '9l8bf',
    age: 23,
    visits: 32,
    status: '',
    image: '/image.png',
  },
  {
    id: 18,
    firstName: 'home',
    lastName: '9l8bf',
    age: 23,
    visits: 32,
    status: '',
    image: '/image.png',
  },
  {
    id: 19,
    firstName: 'home',
    lastName: '9l8bf',
    age: 23,
    visits: 32,
    status: '',
    image: '/image.png',
  },
  {
    id: 20,
    firstName: 'home',
    lastName: '9l8bf',
    age: 23,
    visits: 32,
    status: '',
    image: '/image.png',
  },
  {
    id: 21,
    firstName: 'home',
    lastName: '9l8bf',
    age: 23,
    visits: 32,
    status: '',
    image: '/image.png',
  },
  {
    id: 10,
    firstName: 'population',
    lastName: 'wdpw7',
    age: 1,
    visits: 13,
    status: '',
    image: '/image.png',
  },
  {
    id: 11,
    firstName: 'feet',
    lastName: 'grq7l',
    age: 18,
    visits: 75,
    status: '',
    image: '/image.png',
  },
  {
    id: 12,
    firstName: 'home',
    lastName: '9l8bf',
    age: 23,
    visits: 32,
    status: '',
    image: '/image.png',
  },
  {
    id: 13,
    firstName: 'home',
    lastName: '9l8bf',
    age: 23,
    visits: 32,
    status: '',
    image: '/image.png',
  },
  {
    id: 14,
    firstName: 'home',
    lastName: '9l8bf',
    age: 23,
    visits: 32,
    status: '',
    image: '/image.png',
  },
  {
    id: 15,
    firstName: 'home',
    lastName: '9l8bf',
    age: 23,
    visits: 32,
    status: '',
    image: '/image.png',
  },
  {
    id: 16,
    firstName: 'home',
    lastName: '9l8bf',
    age: 23,
    visits: 32,
    status: '',
    image: '/image.png',
  },
  {
    id: 17,
    firstName: 'home',
    lastName: '9l8bf',
    age: 23,
    visits: 32,
    status: '',
    image: '/image.png',
  },
  {
    id: 18,
    firstName: 'home',
    lastName: '9l8bf',
    age: 23,
    visits: 32,
    status: '',
    image: '/image.png',
  },
  {
    id: 19,
    firstName: 'home',
    lastName: '9l8bf',
    age: 23,
    visits: 32,
    status: '',
    image: '/image.png',
  },
  {
    id: 20,
    firstName: 'home',
    lastName: '9l8bf',
    age: 23,
    visits: 32,
    status: '',
    image: '/image.png',
  },
  {
    id: 21,
    firstName: 'home',
    lastName: '9l8bf',
    age: 23,
    visits: 32,
    status: '',
    image: '/image.png',
  },
  {
    id: 10,
    firstName: 'population',
    lastName: 'wdpw7',
    age: 1,
    visits: 13,
    status: '',
    image: '/image.png',
  },
  {
    id: 11,
    firstName: 'feet',
    lastName: 'grq7l',
    age: 18,
    visits: 75,
    status: '',
    image: '/image.png',
  },
  {
    id: 12,
    firstName: 'home',
    lastName: '9l8bf',
    age: 23,
    visits: 32,
    status: '',
    image: '/image.png',
  },
  {
    id: 13,
    firstName: 'home',
    lastName: '9l8bf',
    age: 23,
    visits: 32,
    status: '',
    image: '/image.png',
  },
  {
    id: 14,
    firstName: 'home',
    lastName: '9l8bf',
    age: 23,
    visits: 32,
    status: '',
    image: '/image.png',
  },
  {
    id: 15,
    firstName: 'home',
    lastName: '9l8bf',
    age: 23,
    visits: 32,
    status: '',
    image: '/image.png',
  },
  {
    id: 16,
    firstName: 'home',
    lastName: '9l8bf',
    age: 23,
    visits: 32,
    status: '',
    image: '/image.png',
  },
  {
    id: 17,
    firstName: 'home',
    lastName: '9l8bf',
    age: 23,
    visits: 32,
    status: '',
    image: '/image.png',
  },
  {
    id: 18,
    firstName: 'home',
    lastName: '9l8bf',
    age: 23,
    visits: 32,
    status: '',
    image: '/image.png',
  },
  {
    id: 19,
    firstName: 'home',
    lastName: '9l8bf',
    age: 23,
    visits: 32,
    status: '',
    image: '/image.png',
  },
  {
    id: 20,
    firstName: 'home',
    lastName: '9l8bf',
    age: 23,
    visits: 32,
    status: '',
    image: '/image.png',
  },
  {
    id: 21,
    firstName: 'home',
    lastName: '9l8bf',
    age: 23,
    visits: 32,
    status: '',
    image: '/image.png',
  },
];
