name: CI
on: [pull_request]

jobs:
  lint:
    name: runner / lint
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 16
          cache: npm

      - name: install
        run: npm install --no-save turbo-linux-64 && npm install

      - name: Check lint
        run: npm run lint

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build
