name: CI
on: [pull_request]

jobs:
  lint:
    name: runner / lint
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: cache node_modules
        id: node_modules_cache_id
        uses: actions/cache@v3
        with:
          path: |
            node_modules
          key: ${{ matrix.os }}-node-v${{ matrix.node }}-deps-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn

      - name: install
        run: yarn install --ignore-engines --frozen-lockfile --immutable
        working-directory: '.'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check lint
        run: yarn lint

      - name: run tsc
        run: yarn type-check
