name: CI for Example
on: [pull_request]

jobs:
  build-vite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - run: npm install --no-save turbo-linux-64
      - run: npm ci
      - run: npm run build
        working-directory: packages/for-ui
      - run: npx yalc publish
        working-directory: packages/for-ui  
      - run: npx yalc link @4design/for-ui
        working-directory: example/vite-app
      - run: npx yalc update
        working-directory: example/vite-app
      - run: npm run build
        working-directory: example/vite-app

  build-nextjs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm  
      - run: npm install --no-save turbo-linux-64
      - run: npm ci
      - run: npm run build
        working-directory: packages/for-ui
      - run: npx yalc publish
        working-directory: packages/for-ui  
      - run: npx yalc link @4design/for-ui
        working-directory: example/nextjs-app
      - run: npx yalc update
        working-directory: example/nextjs-app
      - run: npm run build
        working-directory: example/nextjs-app
