name: 'Publish release'
on:
  release:
    types: [published]
jobs:
  publish-release:
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.RELEASE_PRIVATE_KEY }}
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ steps.generate_token.outputs.token }}
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git fetch
          git checkout -b release origin/release
          git rebase origin/v2
          git push origin release
