name: Release
on:
  push:
    tags:
      - v*.*.*
  release:
    types: [published]

env:
  HUSKY: '0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: yarn
          registry-url: https://registry.npmjs.org

      - name: yarn install
        run: yarn install --frozen-lockfile

      - name: yarn build
        run: yarn build

      - name: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_SECRETS }}
        run: npm publish --access=public
